# jenkins:
# you configure the general information about Jenkins, like nodes or the security-related stuff
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
# unclassified:
# we configure most of the plugin-specific settings under this element
plugins:
  required:
    blueocean: latest
    workflow-aggregator: latest
    pipeline-maven: latest
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                        branch '*/docker-for-mac'
                        extensions {}
                    }
                  }
              }
          }
      }
